name: Beacon_Plugin
main: world.world.BeaconMain
version: "1.21"
api-version: 1.20
commands:
  getbeacon:
    description: Gives a beacon to the player.
    usage: /getbeacon
    aliases: [getb]
  tpbeacon:
    description: Teleports the player to their family's beacon.
    usage: /tpbeacon
    aliases: [tpb]
  start:
    description: 게임을 시작합니다.
    usage: /start
  family:
    description: 가문 관련 명령어
    usage: /family <create|join|leave|info|color>
  setdefaultban: # 명령어 이름
    description: 기본 밴 시간을 설정합니다.
    usage: /<command> <시간(초)>    # 명령어 도움말 출력 형식
    permission: myplugin.setdefaultban # 플레이어가 명령어를 사용할 권한
    permission-message: 권한이 없습니다